/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidad.Cliente;
import entidad.Persona;
import entidad.Usuario;
import utilitario.IntVentanas;
import utilitario.ImagenFondo;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import manejadorDB.controlador.ClienteControlador;
import manejadorDB.controlador.EstadoControlador;
import manejadorDB.controlador.PerfilControlador;
import manejadorDB.controlador.PersonaControlador;
import manejadorDB.controlador.UsuarioControlador;

/**
 *
 * @author ferna
 */
public class DDataCliente extends javax.swing.JDialog implements IntVentanas{

    /**
     * Creates new form Cliente
     */
    private DBuscarClienteEmpleado parentDBuscarClienteEmpleado = null;
    DRegistrarClienteEmpleado parentDRegistrarClienteEmpleado = null;
    private boolean dataModificada = false;
    /*-----------------------------------*/
    private final Persona persona;
    private Cliente cliente;
    /*-----------------------------------*/
    private final PersonaControlador pc = new PersonaControlador();
    private final ClienteControlador cc = new ClienteControlador();
    private final UsuarioControlador uc = new UsuarioControlador();

    public DDataCliente(java.awt.Frame parent, boolean modal, DBuscarClienteEmpleado parentDBuscarClienteEmpleado, Cliente cliente) {
        super(parent, modal);
        initComponents();
                
        this.parentDBuscarClienteEmpleado = parentDBuscarClienteEmpleado;
        this.persona = cliente.getIdpersona();
        this.cliente = cliente;
        
        centrarPantalla(); 
        llenarDatos();        
        
    }

    public DDataCliente(java.awt.Frame parent, boolean modal, Persona persona) {
        super(parent, modal);
        initComponents();
               
        this.persona = persona;
        centrarPantalla(); 
        System.out.println("Persona:   "+this.persona);
        llenarDatos();
    }
    
    
    public DDataCliente(java.awt.Frame parent, boolean modal, Persona persona, DRegistrarClienteEmpleado parentDRegistrarClienteEmpleado) {
        super(parent, modal);
        initComponents();
        this.parentDRegistrarClienteEmpleado = parentDRegistrarClienteEmpleado;
        this.persona = persona;
        centrarPantalla(); 
        System.out.println("Persona:   "+this.persona);
        llenarDatos();
        if (this.parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete != null) {
            bAnadirPaquete.setVisible(false);
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        bAnadirPaquete = new javax.swing.JButton();
        bModificarDatosCliente = new javax.swing.JButton();
        bRemoverDatosCliente = new javax.swing.JButton();
        lbDNI = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidoPaterno = new javax.swing.JLabel();
        lbApellidoMaterno = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        tfDNI = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfNombres = new javax.swing.JTextField();
        tfApellidosPaterno = new javax.swing.JTextField();
        tfApellidosMaterno = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbPerfil1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        bCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bCancelar.setMnemonic('C');
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAceptar.setMnemonic('A');
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bAnadirPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAnadirPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/boxp.png"))); // NOI18N
        bAnadirPaquete.setText("Añadir Paquete");
        bAnadirPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bAnadirPaquete.setIconTextGap(2);
        bAnadirPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirPaqueteActionPerformed(evt);
            }
        });

        bModificarDatosCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bModificarDatosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/editaruser21.png"))); // NOI18N
        bModificarDatosCliente.setBorder(null);
        bModificarDatosCliente.setBorderPainted(false);
        bModificarDatosCliente.setContentAreaFilled(false);
        bModificarDatosCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModificarDatosCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificarDatosCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/editaruser18.png"))); // NOI18N
        bModificarDatosCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/editaruser24.png"))); // NOI18N
        bModificarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarDatosClienteActionPerformed(evt);
            }
        });

        bRemoverDatosCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bRemoverDatosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/removerUser21.png"))); // NOI18N
        bRemoverDatosCliente.setBorder(null);
        bRemoverDatosCliente.setBorderPainted(false);
        bRemoverDatosCliente.setContentAreaFilled(false);
        bRemoverDatosCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bRemoverDatosCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bRemoverDatosCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/removerUser18.png"))); // NOI18N
        bRemoverDatosCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/removerUser24.png"))); // NOI18N
        bRemoverDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverDatosClienteActionPerformed(evt);
            }
        });

        lbDNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDNI.setText("DNI");

        lbCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCodigo.setText("Código");

        lbNombres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombres.setText("Nombres");

        lbApellidoPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoPaterno.setText("Apellido Paterno");

        lbApellidoMaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoMaterno.setText("Apellido Materno ");

        lbCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCorreo.setText("Correo");

        lbTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTelefono.setText("Teléfono");

        lbDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDireccion.setText("Dirección");

        tfDNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfNombres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfApellidosPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfApellidosMaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbPerfil1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPerfil1.setText("Datos Personales");

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addComponent(lbPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pFondoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bAnadirPaquete)
                                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pFondoLayout.createSequentialGroup()
                                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfNombres)
                                            .addComponent(tfApellidosMaterno)
                                            .addComponent(lbApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfCodigo)
                                            .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pFondoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tfDNI)
                                                    .addComponent(tfApellidosPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pFondoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(tfCorreo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bModificarDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bRemoverDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombres)
                            .addComponent(lbApellidoPaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbDNI)
                                    .addComponent(lbCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfApellidosPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pFondoLayout.createSequentialGroup()
                                .addComponent(bModificarDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bRemoverDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pFondoLayout.createSequentialGroup()
                            .addComponent(lbApellidoMaterno)
                            .addGap(27, 27, 27))
                        .addComponent(tfApellidosMaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addComponent(lbTelefono)
                        .addGap(6, 6, 6)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAnadirPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnadirPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirPaqueteActionPerformed
        if(dataModificada){
            modificarDatosPersona();
            JOptionPane.showMessageDialog(this,"Datos Modificados Correctamente", 
                "FELICIDADES", JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/check64.png"));
            dataModificada = false;
        }else{
            agregarCliente();
        }       
        this.dispose();
        
        DRegistrarUnPaquete dRegistrarPaquete = new DRegistrarUnPaquete(null, rootPaneCheckingEnabled,this,persona);
        dRegistrarPaquete.setVisible(true);
    }//GEN-LAST:event_bAnadirPaqueteActionPerformed

    private void bModificarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarDatosClienteActionPerformed
        dataModificada = true ;
        habilitarTextFileDatos(dataModificada);        
    }//GEN-LAST:event_bModificarDatosClienteActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        if(dataModificada){
            modificarDatosPersona();       
            JOptionPane.showMessageDialog(this,"Datos Modificados Correctamente", 
                "FELICIDADES", JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/check64.png"));
        }else{
            if(parentDBuscarClienteEmpleado != null){     
                System.out.println("Vengo de buscar ");
                if(parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete !=  null){
                    if(parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente){
                        System.out.println("asignarCliente  "+parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente);                                
                        parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.asignarCliente(cliente);
                    }else{
                        System.out.println("asignarDestinatario  "+parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente);
                        parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.asignarDestinatario(cliente);
                    } 
                }else{
//                    agregarCliente();
                }
            }else{
                agregarCliente();
            }
        }
        this.dispose();        
        if(parentDBuscarClienteEmpleado != null){     
            if(parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete !=  null){    
                parentDBuscarClienteEmpleado.setVisible(false);
                parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.setVisible(true);
            }else{
                parentDBuscarClienteEmpleado.setVisible(true);
            }
        } 
        if (parentDRegistrarClienteEmpleado != null){
            if(parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete !=  null){
                if(parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente){
                    System.out.println("asignarCliente  "+parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente);                                
                    parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.asignarCliente(cliente);
                }else{
                    System.out.println("asignarDestinatario  "+parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente);
                    parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.asignarDestinatario(cliente);
                } 
            }
            parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.setVisible(true);
        }
//        System.out.println("-  "+parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.buscarRegistrarCliente);
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        if(!dataModificada){            
            if(parentDRegistrarClienteEmpleado != null){     
                pc.eliminar(persona.getIdpersona());
            }
        }
        this.dispose();        
        if(parentDBuscarClienteEmpleado != null){     
            if(parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete !=  null){    
                parentDBuscarClienteEmpleado.setVisible(false);
                parentDBuscarClienteEmpleado.parentDRegistrarUnPaquete.setVisible(true);
            }else{
                parentDBuscarClienteEmpleado.setVisible(true);
            }
        } 
        if (parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete != null){
            parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.setVisible(true);
            parentDRegistrarClienteEmpleado.parentDRegistrarUnPaquete.asignarCliente(cliente);
        } 
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bRemoverDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverDatosClienteActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"Los datos de este cliente se eliminarán \n ¿Desea continuar?",
                "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,                 
                ingresarImagen("/vista/imagen/warning.png"));    
        if(opcion==0){            
            this.dispose();
            if(parentDBuscarClienteEmpleado != null){//sigifica que viene de buscar 
                parentDBuscarClienteEmpleado.setVisible(true);
                uc.eliminar(cliente.getIdusuario().getIdusuario());
                cc.eliminar(cliente.getIdcliente());
                pc.eliminar(cliente.getIdpersona().getIdpersona());
            } else{
                pc.eliminar(persona.getIdpersona());   
            }
        }
    }//GEN-LAST:event_bRemoverDatosClienteActionPerformed
    
    private void habilitarTextFileDatos(boolean activar){
        tfApellidosPaterno.setEditable(activar);
        tfApellidosMaterno.setEditable(activar);
        tfNombres.setEditable(activar);
        tfDNI.setEditable(activar);
        tfCorreo.setEditable(activar);
        tfDireccion.setEditable(activar);
        tfTelefono.setEditable(activar);
        
        tfApellidosPaterno.setEnabled(activar);
        tfApellidosMaterno.setEditable(activar);
        tfNombres.setEnabled(activar);
        tfDNI.setEnabled(activar);
        tfCorreo.setEnabled(activar);
        tfDireccion.setEnabled(activar);
        tfTelefono.setEnabled(activar);        
    }
    
    private void llenarDatos(){
        if(parentDBuscarClienteEmpleado != null){
            tfCodigo.setText(cliente.getCodigo());
            tfApellidosPaterno.setText(cliente.getIdpersona().getApellidopat());
            tfApellidosMaterno.setText(cliente.getIdpersona().getApellidomat());
            tfNombres.setText(cliente.getIdpersona().getNombres());
            tfDNI.setText(cliente.getIdpersona().getDocumento());
            tfCorreo.setText(cliente.getIdpersona().getCorreo());
            tfTelefono.setText(cliente.getIdpersona().getCelular());
        }else{
            tfApellidosPaterno.setText(persona.getApellidopat());
            tfApellidosMaterno.setText(persona.getApellidomat());
            tfNombres.setText(persona.getNombres());
            tfDNI.setText(persona.getDocumento());
            tfCorreo.setText(persona.getCorreo());
            tfTelefono.setText(persona.getCelular());                    
       }
    }
    //Integer idpersona, String documento, String apellidopat, String apellidomat, String nombres, String celular, String correo) {
    private Persona capturarDatos(){
        Persona p = new Persona(persona.getIdpersona(), 
                                tfDNI.getText(), 
                                tfApellidosPaterno.getText(), 
                                tfApellidosMaterno.getText(), 
                                tfNombres.getText(), 
                                tfTelefono.getText(), 
                                tfCorreo.getText());
        return p;
    }
    private void modificarDatosPersona(){
        pc.modificar(capturarDatos());        
        agregarCliente();
    }
       
    
    private void agregarCliente(){
        System.out.println("Agregar   Cliente");
        //-------------------------------------
        PerfilControlador pfc = new PerfilControlador();
        EstadoControlador ec = new EstadoControlador();
        //-------------------------------------
        Usuario u = new Usuario(tfNombres.getText(), tfCorreo.getText(), tfNombres.getText(), pfc.devolverPerfilPorID(3));// idperfil 3 = cliente 
        Cliente c = new Cliente(generarCodigo(persona), persona, uc.crear(u), ec.devolverEstado(1)); // estado 1 actvado
        cc.crear(c);
        cliente = c;
    }
    
    private String generarCodigo(Persona p){
        return ""+p.getApellidopat().substring(0, 2).toUpperCase()+
                  p.getApellidomat().substring(0, 2).toUpperCase()+
                  p.getNombres().substring(0, 2).toUpperCase()+
                  p.getIdpersona()+
                  p.getDocumento().substring(0, 2);
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DDataCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DDataCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DDataCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DDataCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DDataCliente dialog = new DDataCliente(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnadirPaquete;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bModificarDatosCliente;
    private javax.swing.JButton bRemoverDatosCliente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbApellidoMaterno;
    private javax.swing.JLabel lbApellidoPaterno;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbDNI;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbPerfil1;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JPanel pFondo;
    private javax.swing.JTextField tfApellidosMaterno;
    private javax.swing.JTextField tfApellidosPaterno;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
    @Override
    public Icon ingresarImagen(String direccion){
        Icon i = new ImageIcon(getClass().getResource(direccion));
        return i;
    }

    @Override
    public final void centrarPantalla() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //para obtener las dimensiones de la pantalla
        Dimension dimen = this.getSize();
        //igual pero para la ventana
        this.setLocation(
            (pantalla.width - dimen.width) / 2,
            (pantalla.height - dimen.height) / 2);
    }

    @Override
    public void ponerImagenPanel(String direccion,javax.swing.JPanel pFondo) {
        ImagenFondo Imagen = new ImagenFondo(pFondo.getWidth(),pFondo.getHeight(),direccion);
        pFondo.add(Imagen);
        pFondo.repaint();
    }
}
