/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import utilitario.IntVentanas;
import utilitario.ImagenFondo;
import clases.Controlador;
import entidad.Paquete;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Temporizador.TemporizadorAplicacion;
import com.sun.javafx.css.SizeUnits;
import entidad.Cliente;
import entidad.Lugar;
import entidad.Persona;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import manejadorDB.controlador.AeropuertoControlador;
import manejadorDB.controlador.EstadoControlador;
import manejadorDB.controlador.LugarControlador;
import manejadorDB.controlador.PaqueteControlador;
import utilitario.Helper;
import clases.*;

/**
 *
 * @author ferna
 */
public class DRegistrarUnPaquete extends javax.swing.JDialog implements IntVentanas{
    /**
     * Creates new form dRegistrarPaquete
     */
    
    DDataCliente parentDataCliente = null;
    private Persona persona;
    private Cliente emisor;
    private Cliente destinatario;
    private final LugarControlador lc;
    private final AeropuertoControlador ac;
    private PaqueteControlador pc;
    public boolean buscarRegistrarCliente = false;
    
    private List<Lugar> lugares;
    
    public DRegistrarUnPaquete(java.awt.Frame parent, boolean modal, DDataCliente dDataCliente, Persona persona/*,Connection con*/) {
        super(parent, modal);
        initComponents();
        centrarPantalla(); 
        //this.con = con;
        lc = new LugarControlador();
        ac =  new AeropuertoControlador();
        pc = new PaqueteControlador();
        this.parentDataCliente = dDataCliente;
        this.persona = persona;
        llenarCbCiudadesOrigen();
    }
    
    public DRegistrarUnPaquete(java.awt.Frame parent, boolean modal/*,Connection con*/) {
        super(parent, modal);
        initComponents();
        centrarPantalla();         //
        
        lc = new LugarControlador();
        ac =  new AeropuertoControlador();
        pc = new PaqueteControlador();
        
        llenarCbCiudadesOrigen();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        pDataDestinatario = new javax.swing.JPanel();
        tfNombreDestinatario = new javax.swing.JTextField();
        tfApellidoPatDestinatario = new javax.swing.JTextField();
        tfCorreoDestinatario = new javax.swing.JTextField();
        tfTelefonoDestinatario = new javax.swing.JTextField();
        lbNombresDestinatario = new javax.swing.JLabel();
        lbApellidoPatDestinatario = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbDominio = new javax.swing.JLabel();
        cbDominioDestinatario = new javax.swing.JComboBox();
        tfDocumentoDestinatario = new javax.swing.JTextField();
        lbDocumentoDestinatario = new javax.swing.JLabel();
        lbApellidoMatDestinatario = new javax.swing.JLabel();
        tfApellidoMatDestinatario = new javax.swing.JTextField();
        bAnhadirDestinatario = new javax.swing.JButton();
        bBuscarDestinatario = new javax.swing.JButton();
        pDataCliente = new javax.swing.JPanel();
        tfCodigoCliente = new javax.swing.JTextField();
        lbCliente = new javax.swing.JLabel();
        lbApellidoPatCliente = new javax.swing.JLabel();
        tfApellidoPatCliente = new javax.swing.JTextField();
        tfApellidoMatCliente = new javax.swing.JTextField();
        lbNombresApellidoMatCliente = new javax.swing.JLabel();
        tfNombreCliente = new javax.swing.JTextField();
        lbNombreCliente = new javax.swing.JLabel();
        bBuscarCliente = new javax.swing.JButton();
        bAnhadirCliente = new javax.swing.JButton();
        pDataPaquete = new javax.swing.JPanel();
        lbTipoPaquete = new javax.swing.JLabel();
        cbTipoPaquete = new javax.swing.JComboBox();
        cbDestino = new javax.swing.JComboBox();
        lbDestino = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        lbImagenCliente = new javax.swing.JLabel();
        lbPartida = new javax.swing.JLabel();
        cbPartida = new javax.swing.JComboBox();
        bAnadirPaquete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Paquete");
        setResizable(false);

        bCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bCancelar.setMnemonic('C');
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAceptar.setMnemonic('A');
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        pDataDestinatario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Destinatario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        tfNombreDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfApellidoPatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfCorreoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfTelefonoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbNombresDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombresDestinatario.setLabelFor(tfNombreDestinatario);
        lbNombresDestinatario.setText("Nombres *");

        lbApellidoPatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoPatDestinatario.setLabelFor(tfApellidoPatDestinatario);
        lbApellidoPatDestinatario.setText("Apellido Paterno *");

        lbCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCorreo.setLabelFor(tfCorreoDestinatario);
        lbCorreo.setText("Correo *");

        lbTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTelefono.setLabelFor(tfTelefonoDestinatario);
        lbTelefono.setText("Teléfono *");

        lbDominio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDominio.setLabelFor(cbDominioDestinatario);
        lbDominio.setText("Dominio *");

        cbDominioDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDominioDestinatario.setMaximumRowCount(5);
        cbDominioDestinatario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "@gmail.com", "@pucp.edu.pe", "@yahoo.es", "@outlook.com", "@hotmail.com" }));
        cbDominioDestinatario.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDominioDestinatarioActionPerformed(evt);
            }
        });

        tfDocumentoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbDocumentoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDocumentoDestinatario.setLabelFor(tfDocumentoDestinatario);
        lbDocumentoDestinatario.setText("Documento *");

        lbApellidoMatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoMatDestinatario.setLabelFor(tfApellidoMatDestinatario);
        lbApellidoMatDestinatario.setText("Apellido Materno *");

        tfApellidoMatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bAnhadirDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser21.png"))); // NOI18N
        bAnhadirDestinatario.setBorder(null);
        bAnhadirDestinatario.setBorderPainted(false);
        bAnhadirDestinatario.setContentAreaFilled(false);
        bAnhadirDestinatario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAnhadirDestinatario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnhadirDestinatario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser18.png"))); // NOI18N
        bAnhadirDestinatario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUse24r.png"))); // NOI18N
        bAnhadirDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnhadirDestinatarioActionPerformed(evt);
            }
        });


        bBuscarDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser21.png"))); // NOI18N
        bBuscarDestinatario.setBorder(null);
        bBuscarDestinatario.setBorderPainted(false);
        bBuscarDestinatario.setContentAreaFilled(false);
        bBuscarDestinatario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBuscarDestinatario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscarDestinatario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser18.png"))); // NOI18N
        bBuscarDestinatario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser24.png"))); // NOI18N
        bBuscarDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarDestinatarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataDestinatarioLayout = new javax.swing.GroupLayout(pDataDestinatario);
        pDataDestinatario.setLayout(pDataDestinatarioLayout);
        pDataDestinatarioLayout.setHorizontalGroup(
            pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataDestinatarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefonoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbApellidoPatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfApellidoPatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfApellidoMatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addComponent(lbApellidoMatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bAnhadirDestinatario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bBuscarDestinatario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbDocumentoDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDocumentoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombreDestinatario)
                            .addComponent(lbNombresDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCorreoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDominioDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDominio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pDataDestinatarioLayout.setVerticalGroup(
            pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDocumentoDestinatario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNombresDestinatario, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDocumentoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNombreDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbApellidoPatDestinatario)
                                            .addComponent(lbApellidoMatDestinatario))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfApellidoPatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(tfApellidoMatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                        .addComponent(lbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addComponent(tfCorreoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addComponent(lbDominio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDominioDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addComponent(bBuscarDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(bAnhadirDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTelefono)
                .addGap(6, 6, 6)
                .addComponent(tfTelefonoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pDataCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        tfCodigoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfCodigoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoClienteFocusLost(evt);
            }
        });

        lbCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCliente.setText("Código Cliente");

        lbApellidoPatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoPatCliente.setLabelFor(tfApellidoPatCliente);
        lbApellidoPatCliente.setText("Apellido Paterno");

        tfApellidoPatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfApellidoMatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbNombresApellidoMatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombresApellidoMatCliente.setLabelFor(tfApellidoMatCliente);
        lbNombresApellidoMatCliente.setText("Apellido Materno");

        tfNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombreCliente.setLabelFor(tfNombreDestinatario);
        lbNombreCliente.setText("Nombres");

        bBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser21.png"))); // NOI18N
        bBuscarCliente.setBorder(null);
        bBuscarCliente.setBorderPainted(false);
        bBuscarCliente.setContentAreaFilled(false);
        bBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscarCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser18.png"))); // NOI18N
        bBuscarCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser24.png"))); // NOI18N
        bBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarClienteActionPerformed(evt);
            }
        });

        bAnhadirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser21.png"))); // NOI18N
        bAnhadirCliente.setBorder(null);
        bAnhadirCliente.setBorderPainted(false);
        bAnhadirCliente.setContentAreaFilled(false);
        bAnhadirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAnhadirCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnhadirCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser18.png"))); // NOI18N
        bAnhadirCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUse24r.png"))); // NOI18N
        bAnhadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnhadirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataClienteLayout = new javax.swing.GroupLayout(pDataCliente);
        pDataCliente.setLayout(pDataClienteLayout);
        pDataClienteLayout.setHorizontalGroup(
            pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataClienteLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(tfApellidoPatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbApellidoPatCliente))
                    .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCliente))
                .addGap(23, 23, 23)
                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfApellidoMatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombresApellidoMatCliente)
                            .addComponent(tfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAnhadirCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pDataClienteLayout.setVerticalGroup(
            pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataClienteLayout.createSequentialGroup()
                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addComponent(bBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(bAnhadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataClienteLayout.createSequentialGroup()
                                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNombreCliente)
                                    .addComponent(lbCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addComponent(lbApellidoPatCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApellidoPatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addComponent(lbNombresApellidoMatCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApellidoMatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDataPaquete.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Paquete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lbTipoPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTipoPaquete.setLabelFor(cbTipoPaquete);
        lbTipoPaquete.setText("Tipo de Paquete");

        cbTipoPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoPaquete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Documentos", "Caja", "Caja Frágil" }));

        cbDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDestino.setLabelFor(cbDestino);
        lbDestino.setText("Destino");

        lbDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescripcion.setLabelFor(tfDescripcion);
        lbDescripcion.setText("Descripción");

        tfDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbImagenCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbImagenCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagenCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/cajita.png"))); // NOI18N

        lbPartida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPartida.setLabelFor(cbDestino);
        lbPartida.setText("Partida");

        cbPartida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPartida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPartidaItemStateChanged(evt);
            }
        });
        cbPartida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbPartidaFocusGained(evt);
            }
        });
        cbPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPartidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDataPaqueteLayout = new javax.swing.GroupLayout(pDataPaquete);
        pDataPaquete.setLayout(pDataPaqueteLayout);
        pDataPaqueteLayout.setHorizontalGroup(
            pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataPaqueteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pDataPaqueteLayout.createSequentialGroup()
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPartida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDestino)))
                    .addGroup(pDataPaqueteLayout.createSequentialGroup()
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescripcion)
                            .addComponent(cbTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTipoPaquete))
                        .addGap(39, 39, 39)
                        .addComponent(lbImagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDataPaqueteLayout.setVerticalGroup(
            pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataPaqueteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataPaqueteLayout.createSequentialGroup()
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTipoPaquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lbPartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDataPaqueteLayout.createSequentialGroup()
                        .addComponent(lbImagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        bAnadirPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAnadirPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/boxp.png"))); // NOI18N
        bAnadirPaquete.setText("Más Paquetes");
        bAnadirPaquete.setToolTipText("");
        bAnadirPaquete.setActionCommand("");
        bAnadirPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bAnadirPaquete.setIconTextGap(2);
        bAnadirPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnadirPaqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pDataCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDataPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pDataDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAnadirPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addComponent(pDataCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pDataPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addComponent(pDataDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bAnadirPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"Los datos ingresados no se guardarán \n ¿Desea continuar?",
                "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,                 
                ingresarImagen("/vista/imagen/warning.png"));    
        if(opcion==0){
            this.dispose();
            if(parentDataCliente != null){
                parentDataCliente.setVisible(true);
            } 
        }
           
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
//        JOptionPane.showMessageDialog(this,"Paquete Registrado Correctamente", 
//                "FELICIDADES", JOptionPane.PLAIN_MESSAGE,
//                ingresarImagen("/vista/imagen/check64.png"));
        
//                
        Date fechadereg = new Date(new GregorianCalendar().get(Calendar.YEAR)-1900, 
                (new GregorianCalendar().get(Calendar.MONTH)),
                (new GregorianCalendar().get(Calendar.DAY_OF_MONTH)),
                new GregorianCalendar().get(Calendar.HOUR_OF_DAY),
                new GregorianCalendar().get(Calendar.MINUTE),
                new GregorianCalendar().get(Calendar.SECOND) );
        
        Lugar origen = lc.buscar((String) cbPartida.getSelectedItem(), 1).get(0);
        Lugar destino = lc.buscar((String) cbDestino.getSelectedItem(), 1).get(0);
        
        System.out.println("Origen:  "+origen.getCiudad()+"  -   "+"Destino:  "+destino.getCiudad());
                
        LocalDateTime fechaRegistro = TemporizadorAplicacion.getFecha();
        clases.Paquete p = new clases.Paquete((Integer)cbPartida.getSelectedItem(),
                (Integer)cbDestino.getSelectedItem(),fechaRegistro.getHour(),
                asignarIDPaquete(),fechaRegistro);//el 0 es el que tienes que cambiar
        Controlador.AgregarPaquete(p);
        Controlador.EjecutarAlgoritmo(p);
        
       System.out.println(" id :    "+ac.buscarByLugar(origen).size()+"   -  ");
        Paquete paquete = new Paquete(Helper.generarCodigo(2), 
                                    tfDescripcion.getText(), 
                                    fechadereg, 
                                    ac.buscarByLugar(origen).get(0), 
                                    ac.buscarByLugar(destino).get(0), 
                                    destinatario.getIdpersona(),
                                    new EstadoControlador().devolverEstado(3), 
                                    emisor);
        pc.crear(paquete);
        System.out.println("paquete:   "+ paquete.toString());
        this.dispose();
        if(parentDataCliente != null){
            parentDataCliente.setVisible(true);
        } 
    }//GEN-LAST:event_bAceptarActionPerformed

    private void tfCodigoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoClienteFocusLost
        boolean existe=false;
        if(!existe){
//            JOptionPane.showMessageDialog(this,"Código Inválido, Usuario no Existe", 
//                "ERROR", JOptionPane.PLAIN_MESSAGE,
//                ingresarImagen("/imagenes/error.png"));
        }       
//        tfCodigoCliente.requestFocus();
    }//GEN-LAST:event_tfCodigoClienteFocusLost

    private void cbDominioDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDominioDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDominioDestinatarioActionPerformed

    private void bAnadirPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnadirPaqueteActionPerformed
        this.dispose();
        DRegistrarMasPaquetes dRegistrarMasPaquetes;
        if (parentDataCliente != null){
            dRegistrarMasPaquetes = new DRegistrarMasPaquetes(null, rootPaneCheckingEnabled,this);            
        }else{
            dRegistrarMasPaquetes = new DRegistrarMasPaquetes(null, rootPaneCheckingEnabled);         
        }
        dRegistrarMasPaquetes.setVisible(true);
    }//GEN-LAST:event_bAnadirPaqueteActionPerformed

    private void bBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarClienteActionPerformed
        this.dispose();
        buscarRegistrarCliente = true;
        DBuscarClienteEmpleado dBuscarClienteEmpleado = new DBuscarClienteEmpleado(null, rootPaneCheckingEnabled, this);
        dBuscarClienteEmpleado.setVisible(true);   
    }//GEN-LAST:event_bBuscarClienteActionPerformed

    private void bAnhadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnhadirClienteActionPerformed
        this.dispose();
        buscarRegistrarCliente = true;
        DRegistrarClienteEmpleado dRegistrarClienteEmpleado = new DRegistrarClienteEmpleado(null, buscarRegistrarCliente, this);
        dRegistrarClienteEmpleado.setVisible(true);
    }//GEN-LAST:event_bAnhadirClienteActionPerformed

    private void bBuscarDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarDestinatarioActionPerformed
        this.dispose();
        buscarRegistrarCliente = false;
        DBuscarClienteEmpleado dBuscarClienteEmpleado = new DBuscarClienteEmpleado(null, rootPaneCheckingEnabled, this);
        dBuscarClienteEmpleado.setVisible(true);  
    }//GEN-LAST:event_bBuscarDestinatarioActionPerformed

    private void bAnhadirDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnhadirDestinatarioActionPerformed
        this.dispose();
        buscarRegistrarCliente = false;
        DRegistrarClienteEmpleado dRegistrarClienteEmpleado = new DRegistrarClienteEmpleado(null, buscarRegistrarCliente, this);
        dRegistrarClienteEmpleado.setVisible(true);
    }//GEN-LAST:event_bAnhadirDestinatarioActionPerformed

    private void cbPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPartidaMouseClicked
        
    }//GEN-LAST:event_cbPartidaMouseClicked

    private void cbPartidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPartidaItemStateChanged
        if(cbDestino.getItemCount()!=0){
            cbDestino.removeAllItems();              
        }
        lugares.stream().filter((l) -> (!l.getCiudad().equals(cbPartida.getSelectedItem()))).forEach((l) -> {
            cbDestino.addItem(l.getCiudad());
        });
    }//GEN-LAST:event_cbPartidaItemStateChanged

    private void cbPartidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPartidaFocusGained
        
    }//GEN-LAST:event_cbPartidaFocusGained

    /**
     * @param c
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DRegistrarPaquete dialog = new DRegistrarPaquete(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    public void asignarCliente(Cliente c){
        System.out.println("Asignar CLiente");
        this.emisor = c;
        persona = c.getIdpersona();
        llenarDatosCliente();
        
    }
    
    public void asignarDestinatario(Cliente d){
        System.out.println("asignar Destinatario");
        this.destinatario = d;
        llenarDatosDestinatario();
    }
    
    private void llenarDatosCliente(){
        tfCodigoCliente.setText(emisor.getCodigo());
        tfNombreCliente.setText(emisor.getIdpersona().getNombres());
        tfApellidoPatCliente.setText(emisor.getIdpersona().getApellidopat());
        tfApellidoMatCliente.setText(emisor.getIdpersona().getApellidomat());        
    }
    
    private void llenarDatosDestinatario(){
        tfDocumentoDestinatario.setText(destinatario.getIdpersona().getDocumento());
        tfNombreDestinatario.setText(destinatario.getIdpersona().getNombres());
        tfApellidoPatDestinatario.setText(destinatario.getIdpersona().getApellidopat());
        tfApellidoMatDestinatario.setText(destinatario.getIdpersona().getApellidomat());
//        tfCorreoDestinatario.setText();
        tfTelefonoDestinatario.setText(destinatario.getIdpersona().getCelular());
        
        String[] a= destinatario.getIdusuario().getCorreo().split("@");
        tfCorreoDestinatario.setText(a[0]);
        switch(a[1]){
            case "gmail.com":
                cbDominioDestinatario.setSelectedIndex(0);
                break;
            case "pucp.edu.pe":
                cbDominioDestinatario.setSelectedIndex(1);
                break;
            case "yahoo.es":
                cbDominioDestinatario.setSelectedIndex(2);
                break;
            case "outlook.com":
                cbDominioDestinatario.setSelectedIndex(3);
                break;
            case "hotmail.com":
                cbDominioDestinatario.setSelectedIndex(4);
                break;
        }       
    }
    
    private void llenarCbCiudadesOrigen(){        
        lugares = lc.todos();
        lugares.stream().forEach((l) -> {
            cbPartida.addItem(l.getCiudad());
        });
    }
    
    private int asignarIDPaquete(){
        int id=0;
        
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnadirPaquete;
    private javax.swing.JButton bAnhadirCliente;
    private javax.swing.JButton bAnhadirDestinatario;
    private javax.swing.JButton bBuscarCliente;
    private javax.swing.JButton bBuscarDestinatario;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox cbDestino;
    private javax.swing.JComboBox cbDominioDestinatario;
    private javax.swing.JComboBox cbPartida;
    private javax.swing.JComboBox cbTipoPaquete;
    private javax.swing.JLabel lbApellidoMatDestinatario;
    private javax.swing.JLabel lbApellidoPatCliente;
    private javax.swing.JLabel lbApellidoPatDestinatario;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDestino;
    private javax.swing.JLabel lbDocumentoDestinatario;
    private javax.swing.JLabel lbDominio;
    private javax.swing.JLabel lbImagenCliente;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombresApellidoMatCliente;
    private javax.swing.JLabel lbNombresDestinatario;
    private javax.swing.JLabel lbPartida;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTipoPaquete;
    private javax.swing.JPanel pDataCliente;
    private javax.swing.JPanel pDataDestinatario;
    private javax.swing.JPanel pDataPaquete;
    private javax.swing.JPanel pFondo;
    private javax.swing.JTextField tfApellidoMatCliente;
    private javax.swing.JTextField tfApellidoMatDestinatario;
    private javax.swing.JTextField tfApellidoPatCliente;
    private javax.swing.JTextField tfApellidoPatDestinatario;
    private javax.swing.JTextField tfCodigoCliente;
    private javax.swing.JTextField tfCorreoDestinatario;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfDocumentoDestinatario;
    private javax.swing.JTextField tfNombreCliente;
    private javax.swing.JTextField tfNombreDestinatario;
    private javax.swing.JTextField tfTelefonoDestinatario;
    // End of variables declaration//GEN-END:variables

    @Override
    public Icon ingresarImagen(String direccion){
        Icon i = new ImageIcon(getClass().getResource(direccion));
        return i;
    }

    @Override
    public final void centrarPantalla() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //para obtener las dimensiones de la pantalla
        Dimension dimen = this.getSize();
        //igual pero para la ventana
        this.setLocation(
            (pantalla.width - dimen.width) / 2,
            (pantalla.height - dimen.height) / 2);
    }

    @Override
    public void ponerImagenPanel(String direccion,javax.swing.JPanel pFondo) {
        ImagenFondo Imagen = new ImagenFondo(pFondo.getWidth(),pFondo.getHeight(),direccion);
        pFondo.add(Imagen);
        pFondo.repaint();
    }

    private Helper Helper() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
