/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidad.Aeropuerto;
import utiles.IntVentanas;
import utiles.ImagenFondo;
import com.sun.glass.events.KeyEvent;
import entidad.Paquete;
import entidad.Cliente;
import entidad.Estado;
import entidad.Lugar;
import entidad.Persona;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import utiles.Conexion;


//import utilitario.Helper;
//import manejadorDB.controlador.AeropuertoControlador;
//import manejadorDB.controlador.EstadoControlador;
//import manejadorDB.controlador.LugarControlador;
//import manejadorDB.controlador.PaqueteControlador;


/**
 *
 * @author MFGuevaraL
 */

public class DRegistrarPaquetes extends javax.swing.JDialog implements IntVentanas {

    /**
     * Creates new form RegistrarMasPaquetes
     * @param modal
     */

    
    private Persona persona;
    private Cliente emisor;
    private Cliente destinatario;
    /*---------------*/
    //private final LugarControlador lc;
    //private final AeropuertoControlador ac;
    //private final PaqueteControlador pc;
    /*---------------*/
    public boolean buscarRegistrarCliente = false;
    DDataCliente parentDataCliente = null;
    /*---------------*/
    private List<Lugar> lugares;    
    private List<Paquete> paquetes;
    /*---------------*/
    private final DefaultTableModel dtm ;
    private final TableColumnModel tcm;        
    /*--------------*/
    private int presionoAnadir;
    public DRegistrarPaquetes(java.awt.Frame parent, boolean modal, DDataCliente dDataCliente, Cliente emisor/*,Connection con*/) {
        super(parent, modal);
        initComponents();
        centrarPantalla(); 
        /*---------------*/
        dtm = (DefaultTableModel)tPaquetes.getModel();        
        tcm = (TableColumnModel)tPaquetes.getColumnModel();
        /*---------------*/
        //lc = new LugarControlador();
        //ac =  new AeropuertoControlador();
        //pc = new PaqueteControlador();
        /*---------------*/
        this.parentDataCliente = dDataCliente;
        this.emisor = emisor;
        /*---------------*/
        asignarCliente(emisor);
        llenarCbCiudadesOrigen();
        definirTabla();
        asignarIcono();
        habilitarTextFile(false);
        /*---------------*/
        paquetes = new ArrayList<>();
        presionoAnadir = 0;
    }    
          
    public DRegistrarPaquetes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centrarPantalla(); 
        /*---------------*/
        dtm = (DefaultTableModel)tPaquetes.getModel();        
        tcm = (TableColumnModel)tPaquetes.getColumnModel();
        /*---------------*/
        //lc = new LugarControlador();
        //ac =  new AeropuertoControlador();
        //pc = new PaqueteControlador();
        /*---------------*/
        llenarCbCiudadesOrigen();
        definirTabla();
        habilitarTextFile(false);
        /*---------------*/
        paquetes = new ArrayList<>();
        presionoAnadir = 0;        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        pDataCliente = new javax.swing.JPanel();
        tfDocumentoCliente = new javax.swing.JTextField();
        lbDocumentoCliente = new javax.swing.JLabel();
        lbApellidoPatCliente = new javax.swing.JLabel();
        tfApellidoPatCliente = new javax.swing.JTextField();
        tfApellidoMatCliente = new javax.swing.JTextField();
        lbNombresApellidoMatCliente = new javax.swing.JLabel();
        tfNombreCliente = new javax.swing.JTextField();
        lbNombreCliente = new javax.swing.JLabel();
        bBuscarCliente = new javax.swing.JButton();
        bAnhadirCliente = new javax.swing.JButton();
        tfCorreoCliente = new javax.swing.JTextField();
        lbCorreo1 = new javax.swing.JLabel();
        lbDominio1 = new javax.swing.JLabel();
        cbDominioCliente = new javax.swing.JComboBox();
        pDataPaquete = new javax.swing.JPanel();
        lbTipoPaquete = new javax.swing.JLabel();
        cbTipoPaquete = new javax.swing.JComboBox();
        cbDestino = new javax.swing.JComboBox();
        lbDestino = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        lbImagenCliente = new javax.swing.JLabel();
        lbPartida = new javax.swing.JLabel();
        cbPartida = new javax.swing.JComboBox();
        spPaquete = new javax.swing.JScrollPane();
        tPaquetes = new javax.swing.JTable();
        bAnhadir = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bGuardar = new javax.swing.JButton();
        pDataDestinatario = new javax.swing.JPanel();
        tfNombreDestinatario = new javax.swing.JTextField();
        tfApellidoPatDestinatario = new javax.swing.JTextField();
        tfCorreoDestinatario = new javax.swing.JTextField();
        lbNombresDestinatario = new javax.swing.JLabel();
        lbApellidoPatDestinatario = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbDominio = new javax.swing.JLabel();
        cbDominioDestinatario = new javax.swing.JComboBox();
        tfDocumentoDestinatario = new javax.swing.JTextField();
        lbDocumentoDestinatario = new javax.swing.JLabel();
        lbApellidoMatDestinatario = new javax.swing.JLabel();
        tfApellidoMatDestinatario = new javax.swing.JTextField();
        bAnhadirDestinatario = new javax.swing.JButton();
        bBuscarDestinatario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Múltiples Paquetes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bCancelar.setMnemonic('C');
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAceptar.setMnemonic('A');
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        pDataCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tfDocumentoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDocumentoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDocumentoClienteFocusLost(evt);
            }
        });

        lbDocumentoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDocumentoCliente.setText("Documento");

        lbApellidoPatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoPatCliente.setText("Apellido Paterno");

        tfApellidoPatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfApellidoMatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbNombresApellidoMatCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombresApellidoMatCliente.setText("Apellido Materno");

        tfNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombreCliente.setText("Nombres");

        bBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser21.png"))); // NOI18N
        bBuscarCliente.setBorder(null);
        bBuscarCliente.setBorderPainted(false);
        bBuscarCliente.setContentAreaFilled(false);
        bBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscarCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser18.png"))); // NOI18N
        bBuscarCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser24.png"))); // NOI18N
        bBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarClienteActionPerformed(evt);
            }
        });

        bAnhadirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser21.png"))); // NOI18N
        bAnhadirCliente.setBorder(null);
        bAnhadirCliente.setBorderPainted(false);
        bAnhadirCliente.setContentAreaFilled(false);
        bAnhadirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAnhadirCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnhadirCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser18.png"))); // NOI18N
        bAnhadirCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUse24r.png"))); // NOI18N
        bAnhadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnhadirClienteActionPerformed(evt);
            }
        });

        tfCorreoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbCorreo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCorreo1.setText("Correo");

        lbDominio1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDominio1.setText("Dominio");

        cbDominioCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDominioCliente.setMaximumRowCount(5);
        cbDominioCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "@gmail.com", "@pucp.edu.pe", "@yahoo.es", "@outlook.com", "@hotmail.com" }));

        javax.swing.GroupLayout pDataClienteLayout = new javax.swing.GroupLayout(pDataCliente);
        pDataCliente.setLayout(pDataClienteLayout);
        pDataClienteLayout.setHorizontalGroup(
            pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataClienteLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(tfApellidoPatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbApellidoPatCliente))
                            .addComponent(tfDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDocumentoCliente))
                        .addGap(23, 23, 23)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombresApellidoMatCliente)
                            .addComponent(tfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDominioCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfApellidoMatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDominio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAnhadirCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pDataClienteLayout.setVerticalGroup(
            pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataClienteLayout.createSequentialGroup()
                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addComponent(bBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(bAnhadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(tfDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataClienteLayout.createSequentialGroup()
                                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNombreCliente)
                                    .addComponent(lbDocumentoCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addComponent(lbApellidoPatCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApellidoPatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDataClienteLayout.createSequentialGroup()
                                .addComponent(lbNombresApellidoMatCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApellidoMatCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19)
                .addGroup(pDataClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addComponent(lbCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(tfCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pDataClienteLayout.createSequentialGroup()
                        .addComponent(lbDominio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDominioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pDataPaquete.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Paquete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbTipoPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTipoPaquete.setText("Tipo de Paquete");

        cbTipoPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoPaquete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Documentos", "Caja", "Caja Frágil" }));

        cbDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDestino.setText("Destino");

        lbDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescripcion.setText("Descripción");

        tfDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyTyped(evt);
            }
        });

        lbImagenCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbImagenCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagenCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/cajita.png"))); // NOI18N

        lbPartida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPartida.setText("Partida");

        cbPartida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPartida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPartidaItemStateChanged(evt);
            }
        });

        tPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Origen", "Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spPaquete.setViewportView(tPaquetes);

        bAnhadir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAnhadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anadirPaquete30.png"))); // NOI18N
        bAnhadir.setText("Añadir");
        bAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnhadirActionPerformed(evt);
            }
        });

        bEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/eliminarPaquete30.png"))); // NOI18N
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/guardar30.png"))); // NOI18N
        bGuardar.setText("Grabar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataPaqueteLayout = new javax.swing.GroupLayout(pDataPaquete);
        pDataPaquete.setLayout(pDataPaqueteLayout);
        pDataPaqueteLayout.setHorizontalGroup(
            pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataPaqueteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataPaqueteLayout.createSequentialGroup()
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbPartida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfDescripcion)
                                .addComponent(cbTipoPaquete, 0, 172, Short.MAX_VALUE)
                                .addComponent(lbTipoPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbImagenCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addComponent(spPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(bAnhadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pDataPaqueteLayout.setVerticalGroup(
            pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataPaqueteLayout.createSequentialGroup()
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataPaqueteLayout.createSequentialGroup()
                                .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTipoPaquete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbImagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPartida)
                            .addComponent(lbDestino)))
                    .addGroup(pDataPaqueteLayout.createSequentialGroup()
                        .addComponent(bAnhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDataPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDataDestinatario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Destinatario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tfNombreDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfApellidoPatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfCorreoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbNombresDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNombresDestinatario.setText("Nombres");

        lbApellidoPatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoPatDestinatario.setText("Apellido Paterno");

        lbCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCorreo.setText("Correo");

        lbDominio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDominio.setText("Dominio");

        cbDominioDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDominioDestinatario.setMaximumRowCount(5);
        cbDominioDestinatario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "@gmail.com", "@pucp.edu.pe", "@yahoo.es", "@outlook.com", "@hotmail.com" }));

        tfDocumentoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbDocumentoDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDocumentoDestinatario.setText("Documento");

        lbApellidoMatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbApellidoMatDestinatario.setText("Apellido Materno");

        tfApellidoMatDestinatario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bAnhadirDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser21.png"))); // NOI18N
        bAnhadirDestinatario.setBorder(null);
        bAnhadirDestinatario.setBorderPainted(false);
        bAnhadirDestinatario.setContentAreaFilled(false);
        bAnhadirDestinatario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAnhadirDestinatario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnhadirDestinatario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUser18.png"))); // NOI18N
        bAnhadirDestinatario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/anhadirUse24r.png"))); // NOI18N
        bAnhadirDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnhadirDestinatarioActionPerformed(evt);
            }
        });

        bBuscarDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser21.png"))); // NOI18N
        bBuscarDestinatario.setBorder(null);
        bBuscarDestinatario.setBorderPainted(false);
        bBuscarDestinatario.setContentAreaFilled(false);
        bBuscarDestinatario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBuscarDestinatario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscarDestinatario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser18.png"))); // NOI18N
        bBuscarDestinatario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/buscarUser24.png"))); // NOI18N
        bBuscarDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarDestinatarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataDestinatarioLayout = new javax.swing.GroupLayout(pDataDestinatario);
        pDataDestinatario.setLayout(pDataDestinatarioLayout);
        pDataDestinatarioLayout.setHorizontalGroup(
            pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataDestinatarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbDocumentoDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDocumentoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(196, 196, 196)
                        .addComponent(bBuscarDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbApellidoPatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfApellidoPatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfCorreoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombreDestinatario)
                                    .addComponent(lbNombresDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDataDestinatarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfApellidoMatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbApellidoMatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbDominioDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbDominio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(bAnhadirDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pDataDestinatarioLayout.setVerticalGroup(
            pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addComponent(lbDocumentoDestinatario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDocumentoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addComponent(lbNombresDestinatario)
                                .addGap(29, 29, 29))
                            .addComponent(tfNombreDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                .addComponent(lbApellidoPatDestinatario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApellidoPatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                        .addComponent(lbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addComponent(tfCorreoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                    .addGroup(pDataDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbApellidoMatDestinatario)
                                        .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(tfApellidoMatDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(50, 50, 50))
                                .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                                    .addComponent(lbDominio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbDominioDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pDataDestinatarioLayout.createSequentialGroup()
                        .addComponent(bBuscarDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAnhadirDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pDataCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDataDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDataPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addComponent(pDataCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pDataDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pDataPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        if((!tfDocumentoCliente.getText().isEmpty() && !tfDocumentoDestinatario.getText().isEmpty()) ||  !(presionoAnadir == 0)){
            int opcion = JOptionPane.showConfirmDialog(this,"Los datos ingresados no se guardarán \n ¿Desea continuar ?",
                "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/warning.png"));
            if(opcion == 0){
                this.dispose();
            }
        }else{
            this.dispose();
        }        
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
//       JOptionPane.showMessageDialog(this,"Todos los paquete fueron registrados correctamente",
//        "FELICIDADES", JOptionPane.PLAIN_MESSAGE,
//        ingresarImagen("/vista/imagen/check64.png"));
        this.dispose();        
    }//GEN-LAST:event_bAceptarActionPerformed

    private void tfDocumentoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDocumentoClienteFocusLost
        
    }//GEN-LAST:event_tfDocumentoClienteFocusLost

    private void bBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarClienteActionPerformed
        //this.dispose();
        buscarRegistrarCliente = true;
        DBuscarClienteEmpleado dBuscarClienteEmpleado = new DBuscarClienteEmpleado(null, rootPaneCheckingEnabled, this);
        dBuscarClienteEmpleado.setVisible(true);        
    }//GEN-LAST:event_bBuscarClienteActionPerformed

    private void bAnhadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnhadirClienteActionPerformed
        //this.dispose();
        buscarRegistrarCliente = true;
        DRegistrarClienteEmpleado dRegistrarClienteEmpleado = new DRegistrarClienteEmpleado(null, rootPaneCheckingEnabled, this);
        dRegistrarClienteEmpleado.setVisible(true);
    }//GEN-LAST:event_bAnhadirClienteActionPerformed

    private void cbPartidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPartidaItemStateChanged
        if(cbDestino.getItemCount()!=0){
            cbDestino.removeAllItems();
        }
        lugares.stream().filter((l) -> (!l.getCiudad().equals(cbPartida.getSelectedItem()))).forEach((l) -> {
            cbDestino.addItem(l.getCiudad());
        });
    }//GEN-LAST:event_cbPartidaItemStateChanged

    private void bAnhadirDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnhadirDestinatarioActionPerformed
        //this.dispose();
        buscarRegistrarCliente = false;
        DRegistrarClienteEmpleado dRegistrarClienteEmpleado = new DRegistrarClienteEmpleado(null, rootPaneCheckingEnabled, this);
        dRegistrarClienteEmpleado.setVisible(true);
    }//GEN-LAST:event_bAnhadirDestinatarioActionPerformed

    private void bBuscarDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarDestinatarioActionPerformed
        //this.dispose();
        buscarRegistrarCliente = false;
        DBuscarClienteEmpleado dBuscarClienteEmpleado = new DBuscarClienteEmpleado(null, rootPaneCheckingEnabled, this);
        dBuscarClienteEmpleado.setVisible(true);
    }//GEN-LAST:event_bBuscarDestinatarioActionPerformed

    private void bAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnhadirActionPerformed
        if(tfDocumentoCliente.getText().isEmpty() && tfDocumentoDestinatario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese datos de cliente y destinatario", 
                "ERROR", JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/error.png")); 
        }else if(tfDocumentoCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese datos de cliente ", 
                "ERROR", JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/error.png")); 
        }else if(tfDocumentoDestinatario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese datos de destinatario", 
                "ERROR", JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/error.png")); 
        }else if(tfDocumentoCliente.getText().equalsIgnoreCase(tfDocumentoDestinatario.getText())){
            JOptionPane.showMessageDialog(this,"Los datos del cliente deben ser diferentes a los del destinatario", 
                "ERROR", JOptionPane.PLAIN_MESSAGE,
                ingresarImagen("/vista/imagen/error.png")); 
        }else{
            LocalDateTime fechaReg = LocalDateTime.now();
            try{
                 fechaReg= Conexion.mr_adicionales.obtener_fecha_sim();
            }catch(RemoteException ex){
                    
            }
            Date fechadereg;
            fechadereg = new Date();
            fechadereg.setYear(fechaReg.getYear()-1901);
            fechadereg.setMonth(fechaReg.getMonthValue()-1);
            fechadereg.setDate(fechaReg.getDayOfMonth());
            fechadereg.setHours(fechaReg.getHour()-1);
            fechadereg.setMinutes(fechaReg.getMinute());
            fechadereg.setSeconds(fechaReg.getMinute());
            fechadereg.setSeconds(fechaReg.getSecond());
            Lugar origen;
            Lugar destino;
            Aeropuerto aero_origen;
            Aeropuerto aero_destino;
            Estado estado;        
            try {
                origen = Conexion.mr_lugar.buscarPorCiudad_lug((String) cbPartida.getSelectedItem()).get(0);/*lc.buscarPorCiudad((String) cbPartida.getSelectedItem()).get(0);*/
                destino = Conexion.mr_lugar.buscarPorCiudad_lug((String) cbDestino.getSelectedItem()).get(0);
                System.out.println("Origen:  "+origen.getCiudad()+"  -   "+"Destino:  "+destino.getCiudad());
                aero_origen = Conexion.mr_aeropuerto.buscarByLugar_aero(origen).get(0);
                aero_destino = Conexion.mr_aeropuerto.buscarByLugar_aero(destino).get(0);
                estado = Conexion.mr_estado.devolverEstado_est(3);

                /*generar codigo*/
                String codigo = Conexion.mr_adicionales.generarCodigo(2);

                Paquete paquete = new entidad.Paquete(codigo, 
                                            tfDescripcion.getText(), 
                                            fechadereg, 
                                            aero_origen, 
                                            aero_destino, 
                                            destinatario.getIdpersona(),
                                            estado, 
                                            emisor);

                paquetes.add(paquete);
                Object[] fila = new Object[dtm.getColumnCount()];
                    fila[0] = paquete.getCodigounico();
                    fila[1] = paquete.getDescripcion();
                    fila[2] = origen.getCiudad();
                    fila[3] = destino.getCiudad();            
                dtm.addRow(fila);             
            } catch (RemoteException ex) {
                Logger.getLogger(DRegistrarPaquetes.class.getName()).log(Level.SEVERE, null, ex);
            }       
            presionoAnadir++;
        }
    }//GEN-LAST:event_bAnhadirActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        paquetes.stream().forEach((p) -> {
            try {
                //pc.crear(p);
                int cod = Integer.valueOf(p.getCodigounico());
                Date f = p.getFechainicio();
                System.out.println("F:    "+f);
                        
                LocalDateTime fecha = LocalDateTime.of(f.getYear(), f.getMonth() + 1, f.getDate(), f.getHours(), f.getMinutes(), f.getSeconds());
                clases.Paquete paq = new clases.Paquete(p.getIdorigen().getIdaeropuerto(),
                        p.getIddestino().getIdaeropuerto(),p.getFechainicio().getHours(),cod,fecha);
                Conexion.mr_adicionales.ejecutarAlgoritmo(paq);
                Conexion.mr_paquete.crear(p);
            } catch (RemoteException ex) {
                Logger.getLogger(DRegistrarPaquetes.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        JOptionPane.showMessageDialog(this,"Todos los paquete fueron registrados correctamente",
        "FELICIDADES", JOptionPane.PLAIN_MESSAGE,
        ingresarImagen("/vista/imagen/check64.png"));
        bAnhadir.setEnabled(false);
        bGuardar.setEnabled(false);
        bEliminar.setEnabled(false);
        
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int filaSeleccionada;
        try{
            filaSeleccionada = tPaquetes.getSelectedRow();
            if (filaSeleccionada == -1){
                System.out.println("Ninguna Fila");
            }else{
                System.out.println("Se capturo la fila :  "+filaSeleccionada);
                dtm.removeRow(filaSeleccionada);
                paquetes.remove(filaSeleccionada);
            }
        }catch (HeadlessException ex){
            System.out.println("Error en capturar la celda :  "+ex.getMessage());
        }
        presionoAnadir--;
    }//GEN-LAST:event_bEliminarActionPerformed

    private void tfDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyTyped
        char c=evt.getKeyChar(); 
        if(!(Character.isLetter(c)||Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_SPACE)) ) { 
              getToolkit().beep();               
              evt.consume();                              
        } 
    }//GEN-LAST:event_tfDescripcionKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcion = JOptionPane.showConfirmDialog(this,"Los datos ingresados no se guardarán \n ¿Desea continuar?",
            "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
            ingresarImagen("/vista/imagen/warning.png"));
        if(opcion == 0){
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing
 
    public final void asignarCliente(Cliente c){
        if(c != null){
            System.out.println("Asignar CLiente");
            this.emisor = c;
            persona = c.getIdpersona();
            llenarDatosCliente();        
        }        
    }
    
    public void asignarDestinatario(Cliente d){
        System.out.println("asignar Destinatario");
        this.destinatario = d;
        llenarDatosDestinatario();
    }
    
    private void llenarDatosCliente(){
        tfDocumentoCliente.setText(emisor.getIdpersona().getDocumento());
        tfNombreCliente.setText(emisor.getIdpersona().getNombres());
        tfApellidoPatCliente.setText(emisor.getIdpersona().getApellidopat());
        tfApellidoMatCliente.setText(emisor.getIdpersona().getApellidomat());   
        String[] a= emisor.getIdusuario().getCorreo().split("@");
        tfCorreoCliente.setText(a[0]);
        switch(a[1]){
            case "gmail.com":
                cbDominioDestinatario.setSelectedIndex(0);
                break;
            case "pucp.edu.pe":
                cbDominioDestinatario.setSelectedIndex(1);
                break;
            case "yahoo.es":
                cbDominioDestinatario.setSelectedIndex(2);
                break;
            case "outlook.com":
                cbDominioDestinatario.setSelectedIndex(3);
                break;
            case "hotmail.com":
                cbDominioDestinatario.setSelectedIndex(4);
                break;
        }       
    }
    
    private void llenarDatosDestinatario(){
        tfDocumentoDestinatario.setText(destinatario.getIdpersona().getDocumento());
        tfNombreDestinatario.setText(destinatario.getIdpersona().getNombres());
        tfApellidoPatDestinatario.setText(destinatario.getIdpersona().getApellidopat());
        tfApellidoMatDestinatario.setText(destinatario.getIdpersona().getApellidomat());        
        String[] a= destinatario.getIdusuario().getCorreo().split("@");
        tfCorreoDestinatario.setText(a[0]);
        switch(a[1]){
            case "gmail.com":
                cbDominioDestinatario.setSelectedIndex(0);
                break;
            case "pucp.edu.pe":
                cbDominioDestinatario.setSelectedIndex(1);
                break;
            case "yahoo.es":
                cbDominioDestinatario.setSelectedIndex(2);
                break;
            case "outlook.com":
                cbDominioDestinatario.setSelectedIndex(3);
                break;
            case "hotmail.com":
                cbDominioDestinatario.setSelectedIndex(4);
                break;
        }       
    }
    
    private void llenarCbCiudadesOrigen(){
        try {
            lugares = Conexion.mr_lugar.todos_lug();
            if(lugares != null){
                lugares.stream().forEach((l) -> {
                    cbPartida.addItem(l.getCiudad());
                }); 
            }                       
        } catch (RemoteException ex) {
            Logger.getLogger(DRegistrarPaquetes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void definirTabla(){                    
        tcm.getColumn(0).setPreferredWidth(84);
        tcm.getColumn(1).setPreferredWidth(84);
        tcm.getColumn(2).setPreferredWidth(84);
        tcm.getColumn(3).setPreferredWidth(84);           
        
    }
    
    private void habilitarTextFile(boolean activar){
        tfApellidoMatCliente.setEditable(activar);
        tfApellidoPatCliente.setEditable(activar);
        tfNombreCliente.setEditable(activar);
        tfDocumentoCliente.setEditable(activar);
        tfCorreoCliente.setEditable(activar);
        cbDominioCliente.setEditable(activar);
        
        tfApellidoMatDestinatario.setEditable(activar);
        tfApellidoPatDestinatario.setEditable(activar);
        tfNombreDestinatario.setEditable(activar);
        tfDocumentoDestinatario.setEditable(activar);
        tfCorreoDestinatario.setEditable(activar);
        cbDominioDestinatario.setEditable(activar);
    }
      
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DRegistrarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DRegistrarPaquetes dialog = new DRegistrarPaquetes(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnhadir;
    private javax.swing.JButton bAnhadirCliente;
    private javax.swing.JButton bAnhadirDestinatario;
    private javax.swing.JButton bBuscarCliente;
    private javax.swing.JButton bBuscarDestinatario;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JComboBox cbDestino;
    private javax.swing.JComboBox cbDominioCliente;
    private javax.swing.JComboBox cbDominioDestinatario;
    private javax.swing.JComboBox cbPartida;
    private javax.swing.JComboBox cbTipoPaquete;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbApellidoMatDestinatario;
    private javax.swing.JLabel lbApellidoPatCliente;
    private javax.swing.JLabel lbApellidoPatDestinatario;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbCorreo1;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDestino;
    private javax.swing.JLabel lbDocumentoCliente;
    private javax.swing.JLabel lbDocumentoDestinatario;
    private javax.swing.JLabel lbDominio;
    private javax.swing.JLabel lbDominio1;
    private javax.swing.JLabel lbImagenCliente;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombresApellidoMatCliente;
    private javax.swing.JLabel lbNombresDestinatario;
    private javax.swing.JLabel lbPartida;
    private javax.swing.JLabel lbTipoPaquete;
    private javax.swing.JPanel pDataCliente;
    private javax.swing.JPanel pDataDestinatario;
    private javax.swing.JPanel pDataPaquete;
    private javax.swing.JPanel pFondo;
    private javax.swing.JScrollPane spPaquete;
    private javax.swing.JTable tPaquetes;
    private javax.swing.JTextField tfApellidoMatCliente;
    private javax.swing.JTextField tfApellidoMatDestinatario;
    private javax.swing.JTextField tfApellidoPatCliente;
    private javax.swing.JTextField tfApellidoPatDestinatario;
    private javax.swing.JTextField tfCorreoCliente;
    private javax.swing.JTextField tfCorreoDestinatario;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfDocumentoCliente;
    private javax.swing.JTextField tfDocumentoDestinatario;
    private javax.swing.JTextField tfNombreCliente;
    private javax.swing.JTextField tfNombreDestinatario;
    // End of variables declaration//GEN-END:variables

    @Override
    public Icon ingresarImagen(String direccion){
        Icon i = new ImageIcon(getClass().getResource(direccion));
        return i;
    }

    @Override
    public final void centrarPantalla() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //para obtener las dimensiones de la pantalla
        Dimension dimen = this.getSize();
        //igual pero para la ventana
        this.setLocation(
            (pantalla.width - dimen.width) / 2,
            (pantalla.height - dimen.height) / 2);
    }

    @Override
    public void ponerImagenPanel(String direccion,javax.swing.JPanel pFondo) {
        ImagenFondo Imagen = new ImagenFondo(pFondo.getWidth(),pFondo.getHeight(),direccion);
        pFondo.add(Imagen);
        pFondo.repaint();
    }
    
    @Override
    public final void asignarIcono(){
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/vista/imagen/iconoAvion.png"));
        this.setIconImage(icon);
    }
    
}